### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by johnnyshields** [mongoid/mongoid-rspec#193]
There are no recently release version which is compatible with Mongoid 6.0

**Comment by vinpereira** [comment]
It is working for me: https://github.com/vinpereira/ruby-business-day-api/tree/develop
In using mongoid-rspec 1.10.0 and mongoid 6.2.0

**Comment by pranav-g10** [comment]
@vinpereira `1.10.0` is a 4 year old release of mongoid-rspec. The current release is `3.0.0`, but there is no way to use it with mongoid 6 because it's dependency is locked to mongoid `~> 5`. So @johnnyshields 's issue is valid.

This was reported earlier as well in #174 , but for some reason that issue was closed

**Comment by dblock** [comment]
I opened https://github.com/mongoid/mongoid-rspec/issues/196. If you want to help (co)maintain raise a hand, @rodrigopinto let us know if you're around.

**Comment by rodrigopinto** [comment]
Guys, I'll take a look over the weekend to review all the issues and PR's and release a new version to support mongo 6. In addition, I would highlight that maintainers are welcome and we need more of you(#196).

**Comment by dblock** [comment]
https://github.com/mongoid/mongoid-rspec/pull/197 added Mongoid 6 support via @saumyamehta17, so this is getting closer.

**Comment by dblock** [comment]
@saumyamehta17 what's your rubygems.org email please for release permissions?

**Comment by dblock** [comment]
I asked @rodrigopinto or @evansagge to give me rubygems access offline. Ready to release otherwise.

**Comment by dblock** [comment]
And done.
