### ISSUE TITLE
Needs more maintainers

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-rspec#196]
Maybe @rodrigopinto can help passing the baton to people using this? I am happy to step in if you don't have time.

Anyone interested? Add your name and raise a hand.

**Comment by rodrigopinto** [comment]
Community, as @dblock mention I would love having more people maintaining this library. As I mentioned at #177. So, please join raise your hands ☝️ and join us 👫 to keep the library alive.

**Comment by saumyamehta17** [comment]
✋  I am interested. Let me know how can I contribute.

**Comment by dblock** [comment]
Finishing https://github.com/mongoid/mongoid-rspec/pull/195 would be good, add support for mongoid 6.

**Comment by dblock** [comment]
Thanks for finishing #195 @saumyamehta17. Some finishing touches in https://github.com/mongoid/mongoid-rspec/pull/197#issuecomment-355369384 please and I'll help you through the release.

**Comment by dblock** [comment]
Invited @saumyamehta17 who added Mongoid 6 support. I'll continue helping out till we get a clean release via #193.
