### ISSUE TITLE
Doesn't work with Mongoid 7

### ISSUE THREAD

**Issue by stanley90** [mongoid/mongoid-rspec#207]
`lib/mongoid/relations` no longer exists in [Mongoid 7](https://github.com/mongodb/mongoid/tree/7.0-dev/lib/mongoid)

```
LoadError:
  cannot load such file -- mongoid/relations
# /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid-rspec-4.0.0/lib/matchers/associations.rb:1:in `require'
# /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid-rspec-4.0.0/lib/matchers/associations.rb:1:in `<top (required)>'
# /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid-rspec-4.0.0/lib/mongoid/rspec.rb:13:in `require'
# /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid-rspec-4.0.0/lib/mongoid/rspec.rb:13:in `<top (required)>'
# /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid-rspec-4.0.0/lib/mongoid-rspec.rb:1:in `require'
# /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid-rspec-4.0.0/lib/mongoid-rspec.rb:1:in `<top (required)>'
```

**Comment by dblock** [comment]
Looks like beta 7 has been released. Would be helpful to see a PR with travis using it and maybe a fix for the issue above.

**Comment by Simbul** [comment]
Mongoid 7 has been [released](https://rubygems.org/gems/mongoid/versions/7.0.0) on March 12th, so this bug is not against a beta version anymore.
Is there any plan to fix it? I'd love to do it myself, but I don't know `mongoid-rspec` well enough to contribute, unfortunately.

**Comment by dblock** [comment]
There's no plan. Someone needs to contribute a PR for this, please. If you want to help, start by adding mongoid7 to .travis.yml and producing a failing build in a PR, that should help actually implement what's missing.

**Comment by dblock** [comment]
Btw, I am happy to do it this weekend if someone want to contribute [$100 to my charity](https://runwithtfk.org/Profile/PublicPage/61018).

**Comment by dblock** [comment]
Closed via https://github.com/mongoid/mongoid-rspec/pull/212#event-1566707765.
