### ISSUE TITLE
uninitialized constant Mongoid::Contextual::Queryable::Key

### ISSUE THREAD

**Issue by zedtux** [mongoid/mongoid-rspec#214]
I'm using mongoid 5.1.6 and mongoid-rspec 4.0.0 and I have the following error:

```
     NameError:
       uninitialized constant Mongoid::Contextual::Queryable::Key
```

with the following spec:

```ruby
  describe 'Embeds' do
    it { is_expected.to embed_many(:preparation_rows).ordered_by('order_number ASC') }
  end
```

This was working fine with mongoid-rspec 3.x.

I guess the version 4.0.0 is not compatible with mongoid 5?

If so, I guess the [`s.add_dependency 'mongoid', '>= 3.1'`](https://github.com/mongoid/mongoid-rspec/blob/master/mongoid-rspec.gemspec#L21) should be changed so that it requires the compatible version of mongoid.

**Comment by dblock** [comment]
Travis seems to think we're testing that version, so something else is going on?

**Comment by stim371** [comment]
I'm seeing this with:
* mongoid-rspec 4.0.1
* mongoid 4.0.2
* rails 4.2.10

It seems like this is the breaking change https://github.com/mongoid/mongoid-rspec/commit/f6d6b6dd8e78c292a6607792afd4d89e6c9fc6ec

Key was moved from Origin::Key to Mongoid::Criteria::Queryable::Key in mongoid 6, I think.
