### ISSUE TITLE
Gem needs new maintainer(s)

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-rspec#237]
Looks pretty quiet here and https://github.com/mongoid/mongoid-rspec/pull/223 didn't have much reaction. I can help get new maintainers if we don't hear from @rodrigopinto or @saumyamehta17.

@davekrupinski and @javierav, interested in helping out?

**Comment by rodrigopinto** [comment]
Hey there. I think would be nice to have new maintainers @dblock, this gem isn't on my radar for while. I would be happy help to welcome @davekrupinski and @javierav if they interested.

**Comment by javierav** [comment]
Thanks you @dblock for the offer, but currently I'm no longer using MongoDB in my projects!

**Comment by knovoselic** [comment]
Is this gem dead? Seems like there's been no issue/PR activity in at least 8 months, and last commit to master was 17 months ago :(

**Comment by dblock** [comment]
Make PRs!

**Comment by knovoselic** [comment]
@dblock does that mean that the PR will get merged in a timely manner and new gem will be cut? I see two PRs open from 2018 and 2019, so that discourages me to create a new one. I am missing some functionality for which I would create a PR, but don't want to waste my time unless it will get reviewed and hopefully merged.

**Comment by dblock** [comment]
I'll review and merge PRs. If you do a great job I'll volunteer you to maintainer since nobody else seems to want to do it.

**Comment by dblock** [comment]
I merged one of the two outstanding PRs, the other needs a rebase.

**Comment by knovoselic** [comment]
Thanks, I'll submit a PR when it's available. Hopefully in a few days.

**Comment by dblock** [comment]
@sairamsrinivasan made a release, 4.2.0, welcome!
