### ISSUE TITLE
Development flow issue.

### ISSUE THREAD

**Issue by skalibog** [mongoid/mongoid-rspec#243]
Hi, dear contributors. I want to add some new matchers such as Shoulda. But specs aren't work correctly. Its passed only on mongoid 7 without errors.
A list of errors I encountered:

- Rubocop not working with ruby 2.6.* and higher. Need to update gem version and yml file, i think.

- Mongoid version 8 required ruby 2.6 and higher. And Specs are crashed. With unexpected errors.

- Specs working only on mongoid-7.gemspec. What i am doing wrong?

Thanks!

**Comment by dblock** [comment]
You're not doing anything wrong! We haven't had any work on this library for over a year, Travis-CI went MIA, so we need to do some work here. Please contribute a replacement for CI using GHA and we can fix all this, you can inspire yourself from other mongoid projects like https://github.com/mongoid/mongoid-grid_fs which have upgraded.

**Comment by skalibog** [comment]
@dblock Hello Daniel. I was open PR with GHA changes. I need help how to prepare to merge PR #244.
Any help or comment in completing this PR would be appreciated.

**Comment by skalibog** [comment]
Closed by #244.
